version: '3.7'

services:

  chat_engine:
    container_name: chat_engine
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./chat_vol:/usr/src/LiquidityAI
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8001/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    # image: postgres:16
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - ./vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
      - ./postgres_vol:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
     
volumes:
  postgres_vol:
    driver: "local"
